networks:
  backend_net:
    driver: bridge

volumes:
  postgres_data:

services:
  db:
    image: postgres:18.3-alpine3.23
    container_name: atos_logos_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - backend_net

  api:
    image: sa-saopaulo-1.ocir.io/grz6egart44y/atos-logos-api:latest
    container_name: atos_logos_api
    restart: always
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
      PORT: 3000
    depends_on:
      - db
    links:
      - db
    networks:
      - backend_net
